[BITS 32]

;layout:
;struct ChunkManager{
;	vector<Chunk*> loadedChunks;								0
;	tsQueue<ChunkUpdate*> pendingUpdates;						16
;	tsQueue<ChunkGraphicsUpdate*> pendingGraphicsUpdates;		24
;	HyperPlane hyperPlane;										32
;}		96 bytes overall

;layout:
;struct ChunkUpdate{
;	int load;					0
;	Chunk* chunk;				4, used only if it is an unload update
;	int chunkX, chunkZ, chunkW	8, used only if it is a load update
;	HyperPlane hyperplane		20, used only if it is a load update
;}		84 bytes overall

;layout:
;struct ChunkGraphicsUpdate{
;	void* data					0, it is Chunk* if load update, otherwise a renderable*
;	int load;					4
;}		8 bytes overall

;process of loading a chunk:
;
;a ChunkUpdate for loading is found
;the chunk gets generated by chunk_generate
;the physics mesh of the chunk is loaded
;a ChunkGraphicsUpdate is pushed onto the pendingGraphicsUpdates queue
;the ChunkGraphicsUpdate is popped from the queue on the graphics(main) thread
;the renderable of the chunk is generated
;the chunk is pushed into the loadedChunks vector


section .text use32

	global chunkManager_create			;ChunkManager* chunkManager_create()
	
	global chunkManager_load			;void chunkManager_load(ChunkManager* manager, vec3* playerPos3D, int renderDistance)
	
	global chunkManager_getHyperPlane	;HyperPlane* chunkManager_getHyperPlane(ChunkManager* cm)
	global chunkManager_setHyperPlane	;void chunkManager_setHyperPlane(ChunkManager* cm, HyperPlane* ph)
	
	global chunkManager_getPlayerChunk	;void chunkManager_getPlayerChunk(ChunkManager* cm, vec3* playerPos3D, int* chunkX, int* chunkZ, int* chunkW)
	
	extern my_printf
	extern my_free
	extern my_memcpy
	
	extern hyperPlane_create
	
	extern vector_init
	extern tsQueue_init
	
	extern vec4_add
	extern vec4_scale
	
chunkManager_create:
	push ebp
	mov ebp, esp
	
	sub esp, 4				;ChunkManager*
	
	;alloc chunk manager
	push 96
	call my_malloc
	mov dword[ebp-4], eax
	add esp, 4
	
	;init vectors and queues
	mov eax, dword[ebp-4]
	push 4
	push eax
	call vector_init
	add esp, 8
	
	mov eax, dword[ebp-4]
	add eax, 16
	push 512
	push 4
	push eax
	call tsQueue_init
	add eps, 12
	
	mov eax, dword[ebp-4]
	add eax, 24
	push 512
	push 4
	push eax
	call tsQueue_init
	add eps, 12
	
	;init hyperplane
	mov eax, dword[ebp-4]
	add eax, 32
	push eax
	call hyperPlane_create
	
	;set return value
	mov eax, dword[ebp-4]
	
	mov esp, ebp
	pop ebp
	ret
	
	
chunkManager_load:
	push ebp
	push esi
	push edi
	push ebx
	mov ebp, esp
	
	sub esp, 4				;player chunk x					4
	sub esp, 4				;player chunk z					8
	sub esp, 4				;player chunk w					12
	
	
	;calculate player chunk pos
	lea eax, [ebp-12]
	push eax
	add eax, 4
	push eax
	add eax, 4
	push eax
	push dword[ebp+24]
	push dword[ebp+20]
	call chunkManager_getPlayerChunk
	add esp, 20
	
	mov esp, ebp
	pop ebx
	pop edi
	pop esi
	pop ebp
	ret
	
	
chunkManager_setHyperPlane:
	push ebp
	mov ebp, esp
	
	mov eax, dword[ebp+8]
	add eax, 32
	push 64
	push dword[ebp+12]
	push eax
	call my_memcpy
	
	mov esp, ebp
	pop ebp
	ret
	
	
chunkManager_getHyperPlane:
	mov eax, dword[esp+4]
	add eax, 32
	ret
	
chunkManager_getPlayerChunk:
	push ebp
	mov ebp, esp
	
	sub esp, 16				;player pos 4d				16
	sub esp, 16				;helper vec4				32
	
	mov eax, dword[ebp+8]
	add eax, 32				;hyperplane in eax
	
	;calculate player pos 4d
	mov ecx, dword[eax]
	mov dword[ebp-16], ecx
	mov ecx, dword[eax+4]
	mov dword[ebp-12], ecx
	mov ecx, dword[eax+8]
	mov dword[ebp-8], ecx
	mov ecx, dword[eax+12]
	mov dword[ebp-4], ecx
	
	mov eax, dword[ebp+8]
	mov ecx, dword[ebp+12]
	push dword[ecx]
	lea ecx, [eax+48]		;cm.hyperplane.dir1
	push ecx
	lea ecx, [ebp-32]
	push ecx
	call vec3_scale
	lea ecx, [ebp-16]
	push ecx
	push ecx
	call vec3_add
	add esp, 20
	
	mov eax, dword[ebp+8]
	mov ecx, dword[ebp+12]
	push dword[ecx+4]
	lea ecx, [eax+64]		;cm.hyperplane.dir2
	push ecx
	lea ecx, [ebp-32]
	push ecx
	call vec3_scale
	lea ecx, [ebp-16]
	push ecx
	push ecx
	call vec3_add
	add esp, 20
	
	mov eax, dword[ebp+8]
	mov ecx, dword[ebp+12]
	push dword[ecx+8]
	lea ecx, [eax+80]		;cm.hyperplane.dir3
	push ecx
	lea ecx, [ebp-32]
	push ecx
	call vec3_scale
	lea ecx, [ebp-16]
	push ecx
	push ecx
	call vec3_add
	add esp, 20
	
	;calculate the player chunk
	mov eax, dword[ebp+16]
	fld dword[ebp-16]
	fistp dword[eax]
	mov ecx, dword[eax]
	sar ecx, 4
	mov dword[eax], ecx
	
	mov eax, dword[ebp+20]
	fld dword[ebp-8]
	fistp dword[eax]
	mov ecx, dword[eax]
	sar ecx, 4
	mov dword[eax], ecx
	
	mov eax, dword[ebp+24]
	fld dword[ebp-4]
	fistp dword[eax]
	mov ecx, dword[eax]
	sar ecx, 4
	mov dword[eax], ecx
	
	
	mov esp, ebp
	pop ebp
	ret