[BITS 32]

section .rodata use32
	global GAME_STATE_EXIT
	global GAME_STATE_INGAME
	global GAME_STATE_MENU
	global GAME_STATE_SETTINGS
	global GAME_STATE_INIT
	global GAME_STATE_DEINIT

	GAME_STATE_EXIT dd 0
	GAME_STATE_INGAME dd 1
	GAME_STATE_MENU dd 2
	GAME_STATE_SETTINGS dd 3
	GAME_STATE_INIT dd 4
	GAME_STATE_DEINIT dd 5